# Generated by Django 3.0.6 on 2020-05-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField(auto_now_add=True)),
                ('salary', models.IntegerField()),
                ('university', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('grade_year', models.CharField(max_length=20)),
                ('gpa', models.FloatField()),
                ('jobs_applied', models.IntegerField()),
                ('job_role', models.CharField(max_length=30)),
                ('purks', models.TextField(max_length=300)),
                ('prev_exp_num', models.IntegerField()),
                ('prev_exp_detail', models.TextField(max_length=300)),
                ('comment', models.TextField(max_length=300)),
            ],
        ),
    ]
