# Generated by Django 3.0.6 on 2020-05-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade_year',
            field=models.CharField(choices=[('1', 'Freshman'), ('2', 'Sophmore'), ('3', 'Junior'), ('4', 'Senior')], max_length=20),
        ),
    ]
