# Generated by Django 3.0.6 on 2020-05-24 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200524_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='purks',
            new_name='perks',
        ),
    ]
