# Generated by Django 3.0.6 on 2020-05-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200524_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='comment',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='jobs_applied',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='perks',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='prev_exp_detail',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
