# Generated by Django 3.0.6 on 2020-05-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20200524_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade_year',
            field=models.CharField(choices=[('Freshman', 'Freshman'), ('Sophmore', 'Sophmore'), ('Junior', 'Junior'), ('Senior', 'Senior')], max_length=20),
        ),
    ]
