# Generated by Django 3.0.6 on 2020-05-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20200525_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='comment',
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
