# Generated by Django 3.0.6 on 2020-05-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20200525_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
