# Generated by Django 3.0.6 on 2021-01-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20210126_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(default='N/A', max_length=30),
        ),
    ]
