# Generated by Django 3.0.6 on 2021-01-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20210126_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='salary',
            field=models.FloatField(),
        ),
    ]
