# Generated by Django 3.0.6 on 2021-02-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20210127_2249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Interns',
        ),
    ]
